/* registry.js — 唯一菜单事实源。画廊首页据此渲染卡片。
   status: 'live' 已建可玩 | 'soon' 即将上线（卡片置灰）
   disclaimer:true → 涉医/法/财，结果区强制免责声明
   *_en 字段：英文模式（localStorage['site.lang']==='en'）时由 shared/app.js 的 GG.meta 合并 */
window.DEMOS = [
  // 产业, slug, 标题, 一句话, emoji, accent
  { slug:'cardna',       industry:'汽车', industry_en:'Auto', title:'购车品味 DNA', title_en:'Car Taste DNA',
    tagline:'滑+答 → 品味画像 · 荐车 · 车企眼里的你', tagline_en:'Swipe + answer → taste profile · car picks · how automakers see you', emoji:'🧬', accent:'#4b54c9', status:'live' },
  { slug:'style-dna',    industry:'时尚', industry_en:'Fashion', title:'自拍色彩诊断', title_en:'Selfie Color Analysis',
    tagline:'一张自拍 → 色彩季型 + 配色板', tagline_en:'One selfie → color season + palette', emoji:'🎨', accent:'#c2569b', status:'live' },
  { slug:'alta',         industry:'时尚', industry_en:'Fashion', title:'场合穿搭', title_en:'Occasion Styling',
    tagline:'连淘宝导入买过的衣服 + 上传想搭的 → AI 出整套 + 缺的直接给购买链接', tagline_en:'Import past buys + upload a piece → AI full look + buy links for the gaps', emoji:'👗', accent:'#9b5cc2', status:'live' },
  { slug:'fortuna',      industry:'金融', industry_en:'Finance', title:'AI 财务管家', title_en:'AI Money Manager',
    tagline:'体检 → 设目标 → 配置 + 蒙特卡洛达成概率 + 行动计划', tagline_en:'Checkup → set goals → allocation + Monte Carlo odds + action plan', emoji:'🧭', accent:'#1f9e8f', status:'live', disclaimer:true },
  { slug:'oboe',         industry:'教育', industry_en:'Education', title:'秒变一门课', title_en:'Topic to Course',
    tagline:'输入主题 → 迷你课 → 学完测掌握度、揪薄弱章', tagline_en:'Type a topic → mini course → mastery test that finds weak chapters', emoji:'📚', accent:'#3a7bd5', status:'live' },
  { slug:'adaptive-quiz',industry:'教育', industry_en:'Education', title:'自适应测验', title_en:'Adaptive Quiz',
    tagline:'答题 → 难度自适应 → 预测分 + 定位能力边界、专项攻顶', tagline_en:'Answer → difficulty adapts → predicted score + ability boundary + targeted drill', emoji:'🧠', accent:'#5a6fd5', status:'live' },
  { slug:'final-round',  industry:'招聘', industry_en:'Hiring', title:'模拟面试', title_en:'Mock Interview',
    tagline:'选岗 → 答行为题 → 即时反馈 → 面试官追你第二刀', tagline_en:'Pick a role → behavioral questions → instant feedback → the interviewer’s follow-up cut', emoji:'🎤', accent:'#3d6fe0', status:'live' },
  { slug:'ubie',         industry:'医疗', industry_en:'Health', title:'症状自助分诊', title_en:'Symptom Self-Triage',
    tagline:'描述症状 → 追问 → 分级 + 该挂哪个科 + 就诊速览卡', tagline_en:'Describe symptoms → follow-ups → triage level + which department + visit card', emoji:'🩺', accent:'#1f9bb3', status:'live', disclaimer:true },
  { slug:'nl-home',      industry:'房产', industry_en:'Real Estate', title:'一句话找房', title_en:'One-line Home Search',
    tagline:'一句话描述 → 解析约束匹配房源 + 哪条心愿最该松(松开重搜解锁更多)', tagline_en:'One line → parsed constraints match homes + which wish to relax (relax & re-search for more)', emoji:'🏠', accent:'#2f8fd4', status:'live' },
  { slug:'mindtrip',     industry:'旅行', industry_en:'Travel', title:'行程 + 地图', title_en:'Itinerary + Map',
    tagline:'想去哪打哪 → 懂行逐时行程 + 交互地图', tagline_en:'Name any city → expert hour-by-hour plan + interactive map', emoji:'🗺️', accent:'#0fa3a3', status:'live' },
  { slug:'dinner',       industry:'餐饮', industry_en:'Food', title:'今天吃什么', title_en:'What’s for Dinner',
    tagline:'冰箱有啥 · 先吃快坏的 · 排一周，都从这问起', tagline_en:'What’s in the fridge · eat what expires first · plan the week', emoji:'🍲', accent:'#e0651f', status:'live' },
  { slug:'insure-need',  industry:'保险', industry_en:'Insurance', title:'该买多少保', title_en:'How Much Coverage',
    tagline:'答生活问题 → 保额/险种建议 + 一年多少钱(占收入几成·先买哪个)', tagline_en:'Answer life questions → coverage advice + yearly cost (% of income · what to buy first)', emoji:'🛡️', accent:'#2b7fae', status:'live', disclaimer:true },
  { slug:'matchmaker',   industry:'约会', industry_en:'Dating', title:'对话式精配', title_en:'Conversational Matchmaking',
    tagline:'只给你一个人 · 既说般配，也说哪里要磨合', tagline_en:'One candidate only · why you fit, and where you’ll need to grind', emoji:'💞', accent:'#e0577f', status:'live' },
  { slug:'pet-health',   industry:'宠物', industry_en:'Pets', title:'宠物拍照自检', title_en:'Pet Photo Check',
    tagline:'拍眼/皮肤 → 健康分 + 观察项 → 复查看好转还是恶化', tagline_en:'Snap eyes/skin → health score + watch items → recheck to track better or worse', emoji:'🐾', accent:'#c98a2b', status:'live', disclaimer:true },
  { slug:'pet-vet',      industry:'宠物', industry_en:'Pets', title:'AI 兽医病历助手', title_en:'AI Vet Records Assistant',
    tagline:'问诊速记 → SOAP病历 + 鉴别诊断 + 出院医嘱 + 费用预估', tagline_en:'Consult notes → SOAP record + differentials + discharge plan + cost estimate', emoji:'🩺', accent:'#157a6e', status:'live', disclaimer:true },
  { slug:'coddle',       industry:'母婴', industry_en:'Parenting', title:'育儿 + 产后陪伴', title_en:'Parenting + Postpartum Companion',
    tagline:'宝宝按月龄 / 妈妈按产后 → 个性化指引 + 附近服务', tagline_en:'Baby by month / mom by postpartum stage → tailored guidance + nearby services', emoji:'🍼', accent:'#d77a98', status:'live', disclaimer:true },
  { slug:'mood-journal', industry:'心理', industry_en:'Mental Health', title:'心情日记', title_en:'Mood Journal',
    tagline:'写心情 → 情绪曲线 + 词云', tagline_en:'Write your mood → emotion curve + word cloud', emoji:'🌤️', accent:'#7a8fd4', status:'live', disclaimer:true },
  { slug:'unmask',       industry:'游戏', industry_en:'Games', title:'不被看穿', title_en:'Unreadable',
    tagline:'剪刀石头布 · 出手前先看「它眼中的你」· 被猜中就输', tagline_en:'Rock-paper-scissors · see how it reads you before you throw · get read, you lose', emoji:'🎭', accent:'#6457e8', status:'live' },
  // ── 出海 / 外贸 · AI 时代特有的跨境商业模式 ──
  { slug:'loka',         industry:'跨境电商', industry_en:'Cross-border', title:'出海本地化', title_en:'Go-Global Localization',
    tagline:'一件商品 → 多国原生 listing + 合规提示', tagline_en:'One product → native listings per country + compliance notes', emoji:'🌐', accent:'#1f8a70', status:'live' },
  { slug:'niche',        industry:'跨境电商', industry_en:'Cross-border', title:'蓝海选品雷达', title_en:'Blue-ocean Product Radar',
    tagline:'一个大类 → 扫出还没杀红的细分蓝海', tagline_en:'One category → scan out niches not yet bloodbathed', emoji:'🧭', accent:'#8a5cd1', status:'live' },
  { slug:'landed',       industry:'跨境电商', industry_en:'Cross-border', title:'到岸价对比', title_en:'Landed Cost Compare',
    tagline:'输入成本 → 各国到岸价 + 利润，先打哪国', tagline_en:'Enter cost → landed price + margin per country, where to launch first', emoji:'🚢', accent:'#2c5fa8', status:'live' },
  { slug:'ping',         industry:'留学', industry_en:'Study Abroad', title:'留学生身份合规导航', title_en:'Student Visa Compliance Navigator',
    tagline:'一句话描述身份 → 个性化路线图 + 政策雷达 + 家长安心卡', tagline_en:'One line about your status → personal roadmap + policy radar + parent peace-of-mind card', emoji:'🛟', accent:'#1f8c8c', status:'live', disclaimer:true },
];
