/* final-round — 模拟面试题库。每岗 4~6 道行为面试题（STAR 类）。 */
window.FINAL_ROUND = {
  ROLES: [
    {
      key: 'pm',
      label: GG.T('产品经理', 'Product Manager'),
      emoji: '📱',
      questions: [
        GG.T('请讲一个你主导、从 0 到 1 推动落地的产品功能，你是怎么定义问题、做取舍、并衡量成败的？',
             'Tell me about a product feature you owned and drove from zero to one. How did you frame the problem, make trade-offs, and measure success?'),
        GG.T('讲一次你和研发 / 设计在优先级上发生严重分歧的经历，你最后是怎么对齐并推动决策的？',
             'Tell me about a time you had a serious disagreement with engineering or design over priorities. How did you get aligned and drive the decision?'),
        GG.T('描述一个你做过但数据没达预期的功能，你后来怎么复盘、止损或迭代？',
             'Describe a feature you shipped that missed its metrics. How did you run the retro, cut losses, or iterate?'),
        GG.T('说一次你靠数据 / 用户调研推翻了团队（或自己）原本想当然的判断的经历。',
             'Tell me about a time data or user research overturned an assumption your team (or you yourself) had taken for granted.'),
        GG.T('讲一个你在资源 / 时间严重不足时，如何砍需求、保住核心价值并按时交付的项目。',
             'Tell me about a project where time or resources were badly constrained — how did you cut scope, protect the core value, and still ship on time?'),
      ],
    },
    {
      key: 'fe',
      label: GG.T('前端工程师', 'Frontend Engineer'),
      emoji: '💻',
      questions: [
        GG.T('讲一次你主导的前端性能优化：当时瓶颈是什么、你做了哪些动作、首屏 / 指标提升了多少？',
             'Walk me through a frontend performance optimization you led: what was the bottleneck, what did you do, and how much did first paint or your key metrics improve?'),
        GG.T('描述一个你排查过的、很难复现的线上 bug，你是怎么定位根因并彻底解决的？',
             'Describe a hard-to-reproduce production bug you investigated. How did you track down the root cause and fix it for good?'),
        GG.T('说一次你推动团队做技术重构 / 升级（如框架迁移、组件库统一）的经历，怎么说服大家并控制风险？',
             'Tell me about a time you drove a refactor or tech upgrade (framework migration, unifying the component library). How did you win buy-in and manage the risk?'),
        GG.T('讲一个你和后端 / 设计就接口或还原度反复拉扯的协作经历，最后怎么收敛的？',
             'Tell me about a drawn-out back-and-forth with backend or design over API contracts or design fidelity. How did you bring it to a close?'),
        GG.T('描述一次你在 deadline 很紧时，如何取舍技术方案、保证质量又按时上线的项目。',
             'Describe a project with a tight deadline — how did you trade off the technical approach to protect quality and still launch on time?'),
      ],
    },
    {
      key: 'ops',
      label: GG.T('运营', 'Growth & Operations'),
      emoji: '📈',
      questions: [
        GG.T('讲一个你从 0 策划并落地的活动 / 增长项目，目标是什么、你做了哪些动作、最终拉来多少用户或转化？',
             'Tell me about a campaign or growth project you planned and executed from scratch: what was the goal, what did you do, and how many users or conversions did it bring in?'),
        GG.T('描述一次你负责的核心指标下滑，你是怎么定位原因并把它拉回来的？',
             'Describe a time a core metric you owned slipped. How did you diagnose the cause and pull it back up?'),
        GG.T('说一次你用很低的预算 / 资源撬动了一个超预期结果的运营经历。',
             'Tell me about a time you leveraged a tiny budget or minimal resources into a result that beat expectations.'),
        GG.T('讲一个你做的用户分层 / 精细化运营案例，怎么设计策略、效果如何量化？',
             'Walk me through a user segmentation or lifecycle operations case you ran: how did you design the strategy, and how did you quantify the impact?'),
        GG.T('描述一次活动或项目效果远低于预期的经历，你后来怎么复盘并改进的？',
             'Describe a campaign or project that fell far short of expectations. How did you run the post-mortem and improve?'),
      ],
    },
    {
      key: 'sales',
      label: GG.T('销售', 'Sales'),
      emoji: '🤝',
      questions: [
        GG.T('讲一个你拿下的最有挑战的大单：客户当时的顾虑是什么、你做了哪些动作、最终成交金额多少？',
             'Tell me about the toughest big deal you ever closed: what were the customer’s concerns, what did you do, and what was the final deal size?'),
        GG.T('描述一次你把一个濒临流失 / 长期僵持的客户重新盘活的经历。',
             'Describe a time you revived an account that was about to churn or had been stuck in a stalemate for months.'),
        GG.T('说一次你在严重落后于业绩目标时，是怎么调整打法、最后追回 / 完成指标的。',
             'Tell me about a time you were far behind quota. How did you change your playbook and claw your way back to target?'),
        GG.T('讲一个你面对强势竞品、靠差异化打法赢下客户的经历。',
             'Tell me about a deal you won against a strong competitor by playing to your differentiation.'),
        GG.T('描述一次你丢掉的关键订单，你事后怎么复盘、并把教训用到了下一单。',
             'Describe a key deal you lost. How did you debrief afterwards, and how did you apply the lesson to the next one?'),
      ],
    },
    {
      key: 'ds',
      label: GG.T('数据分析', 'Data Analyst'),
      emoji: '📊',
      questions: [
        GG.T('讲一个你的数据分析真正驱动了业务决策的项目：问题是什么、你怎么分析、最终带来了什么改变？',
             'Tell me about a project where your analysis genuinely drove a business decision: what was the question, how did you approach it, and what changed as a result?'),
        GG.T('描述一次你从一堆杂乱数据里挖出关键洞察、并说服业务方采纳的经历。',
             'Describe a time you dug a key insight out of messy data and convinced business stakeholders to act on it.'),
        GG.T('说一次你搭建 / 优化了一套指标体系或看板，它后来怎么帮团队提效或决策的。',
             'Tell me about a metrics framework or dashboard you built or overhauled — how did it later help the team move faster or decide better?'),
        GG.T('讲一个你发现并纠正了一个被大家长期误信的数据 / 结论的经历。',
             'Tell me about a time you caught and corrected a number or conclusion the team had wrongly trusted for a long time.'),
        GG.T('描述一次分析结论和业务方直觉强烈冲突时，你是怎么验证并推动落地的。',
             'Describe a time your conclusion clashed head-on with a stakeholder’s intuition. How did you validate it and drive it through?'),
      ],
    },
  ],
};
